Repository StephenRhoades/CS321, pull requests merged in 2024-12, with the labels that each got.

#76 make quick add #72
  manifest.json
  scripts/background.js
  scripts/views/openView.js
Labels: enhancement

#81 make feedback/completion of tasks #73
  README.md
  css/pages/calendarView.css
  css/pages/listView.css
  scripts/views/calendarView.js
  scripts/views/listView.js
Labels: enhancement

#82 Settings implementation
  css/openViewStyles.css
  css/pages/calendarView.css
  css/pages/listView.css
  css/pages/settings.css
  css/pages/taskPage.css
  html/openView.html
  html/pages/calendarView.html
  html/pages/listView.html
  html/pages/settings.html
  html/pages/taskPage.html
  scripts/settings.js
  scripts/taskPage.js
  scripts/views/calendarView.js
  scripts/views/listView.js
  scripts/views/openView.js
Labels: User Interface

#85 Just cleaned up the read me and moved the version to 1.0.0
  README.md
  manifest.json
Labels: documentation

#86 Fixed alerts and recurring tasks
  scripts/task.js
Labels: bug
