Repository StephenRhoades/CS321, pull requests merged in 2024-11, with the labels that each got.

#39 Write method names and specifications for openView
  scripts/views/openView.js
Labels: documentation, enhancement, Script

#29 Add Methods and Specs to calendarView.js
  scripts/views/calendarView.js
Labels: documentation, enhancement, Script

#27 Write method names and specifications for listView
  scripts/views/listView.js
Labels: documentation, enhancement

#37 Added Task modify and documented
  scripts/task.js
Labels: documentation, enhancement

#40 WIP - added modify functions
  scripts/task.js
  scripts/taskPage.js
Labels: documentation, enhancement, help wanted

#28 Write method names and specifications for background & JUnit testing for listView
  css/openViewStyles.css
  css/pages/calendarView.css
  html/openView.html
  html/pages/calendarView.html
  html/pages/listView.html
  html/pages/settings.html
  html/pages/taskPage.html
  manifest.json
  scripts/background.js
  scripts/task.js
  scripts/tests/listViewTest.js
  scripts/views/calendarView.js
  scripts/views/listView.js
Labels: documentation, enhancement, Script, Test

#45 Calendar UI #44
  css/pages/calendarView.css
  html/pages/calendarView.html
  scripts/views/calendarView.js
Labels: User Interface

#56 JUnit testing for background
  html/openView.html
  html/pages/calendarView.html
  html/pages/listView.html
  html/pages/settings.html
  html/pages/taskPage.html
  scripts/background.js
  scripts/taskPage.js
  scripts/tests/backgroundTest.js
  scripts/tests/listViewTest.js
  scripts/tests/testBase.js
Labels: enhancement, Script, Test

#67 66 task page implementation
  css/pages/taskPage.css
  html/pages/calendarView.html
  html/pages/taskPage.html
  package.json
  scripts/taskPage.js
  scripts/views/listView.js
Labels: enhancement, User Interface

#69 make calendarview opening page #68
  css/pages/calendarView.css
  html/pages/calendarView.html
  html/pages/listView.html
  html/pages/settings.html
  manifest.json
Labels: Architecture

#71 get task editing working #70
  css/pages/calendarView.css
  css/pages/listView.css
  css/pages/taskPage.css
  html/pages/taskPage.html
  scripts/taskPage.js
  scripts/views/calendarView.js
  scripts/views/listView.js
Labels: enhancement
